name: sarchiver
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/surajkarki66/SArchiver

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
