name: sarchiver
description: "A CLI app to compress and decompress various files into various compression formats. Supported compression formats: Zip, Tar"
version: 0.0.3
homepage: https://github.com/surajkarki66/SArchiver
repository: https://github.com/surajkarki66/SArchiver

executables:
  sarchiver:

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  archive: ^3.3.7
  args: ^2.4.0
  cli_spinner: ^1.0.4
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
